name = "soumya-dahal-portfolio"
compatibility_date = "2024-11-25"
pages_build_output_dir = "./dist"

[env.production]
zone_id = "your-zone-id"
account_id = "your-account-id"

[[routes]]
pattern = "/*"
custom_domain = "soumyadahal.com.np"
